### ISSUE TITLE
purgeNode not removing implicit dependencies

### ISSUE THREAD

**Issue by jauhl** [goessner/mec2#12]
```javascript
{
    id:"beam",
    dt: 2 / 360,
    gravity:true,
    dirty: true,
    nodes: [
        {id:'A0',x:100,y:100,base:true},
        {id:'A',x:100,y:150},
        {id:'B',x:350,y:220},
        {id:'B0',x:300,y:100,base:true}
    ],
    constraints: [
        { id:'a',p1:'A0',p2:'A',len:{type:'const'} },
        { id:'b',p1:'A', p2:'B',len:{type:'const'} },
        { id:'c',p1:'B0', p2:'B',len:{type:'const'} }
    ],
    shapes: [
        {type:'beam',p:'B0',wref:'c',len:175}
    ]
}
```
When purging node `B` of the model above, constraint `c` is removed while the shape depending on it is not.

**Comment by goessner** [comment]
Yes ... registering constraint 'b' and 'c' as dependents is not enough. As constraints itself can have dependents, those have to be added to the list also.

We are lucky that we have no circular dependencies now .. and hopefully in future also.

It works now with last commit.

Please note, that `dirty` flag is depricated and will be removed soon.

Also the `dt` property is useless now, as `model.timer.dt` will be constantly updated by every call of `model.tick` function.

Please remove them from all models in future.

**Comment by jauhl** [comment]
fixed

**Comment by jauhl** [comment]
fixed
