### ISSUE TITLE
ori.inputCallbk does not work for negative values

### ISSUE THREAD

**Issue by klawr** [goessner/mec2#15]
I had a problem to implement a slider which should move between -180 and 180 degree.
Also values above 360 degree do not work as intended.

Possible solution would be to modify [the inputCallbk function](https://github.com/goessner/mec2/blob/master/src/mec.constraint.js#L451):

```js
ori.inputCallbk = (w) => {
    const val = w > 0 ? +w%360 : +w%360+360;
    ori.local_t = val*Math.PI/180*ori.Dt/ori.Dw;
};
```

**Comment by jauhl** [comment]
I think this behavior is intended.

Please note that the range of your input must be consistent with the `Dw` property of your drive (eg. `min=”0” max=”720”` and `Dw: 4*Math.PI`). I can’t reproduce erros for values over 360°, can you provide an example?

While negative values are not supported you can shift them to a positive range, so -180°<phi<180° -> 
0°<phi<360° with a constraint property `w0:2*Math.PI` (or simply define the initial node positions appropriately).

**Comment by klawr** [comment]
`<input type="range" id="slider" min="270" max="450" step="1">`
works only if the value is below 360.
Maybe I am using this wrong.
I set ori with `"ori":{ "type":"drive","input":true } }`
and then issue this function
```js
const callbk = mcSteph.constraintById('B0B').ori.inputCallbk;
slider.addEventListener('input', () => {
    callbk(slider.value)
});
```

**Comment by jauhl** [comment]
For that case using
`<input type="range" id="slider" min="0" max="180" step="1">`
and
`"ori":{ "type":"drive","w0":270*Math.PI/180,"Dw":Math.PI,"input":true } }`
should work.

**Comment by klawr** [comment]
I see that my example is staged and I could change the setup to solve this case.
Just felt like this is not intended and could need an improvement, but if this is intended this issue can be closed.

**Comment by goessner** [comment]
You are allowed to use any range with your slider .
```html
<input id="slider" type="range" min="-180" max="180" value="-180" step="1"/>
```
All you need to do, is to provide a normalized angle in [deg] to the ori callback function then:

```js
const slider = document.getElementById('slider'),
         oriCallbk = model.constraintById('a').ori.inputCallbk;
slider.addEventListener("input", e => oriCallbk(+e.target.value + 180), false);
```
* Note the '+' before `e.target.value` ... we need to make it a number as input's always give you strings.
* You are not required to modify the `w0` property of the ori object. `w0` is always the offset added to the normalized input angle. So synchronizing the input range to `w0` makes absolute sense.
