### ISSUE TITLE
error handling in latest commit

### ISSUE THREAD

**Issue by jauhl** [goessner/mec2#16]
With the latest commit error messages where implemented.
This is the current form of `mec.model.init()`:
https://github.com/goessner/mec2/blob/6aeff0ad84aa82bf733b4808d6d0b31501f680c6/src/mec.model.js#L59-L84

This method looked different in the commit before that, which contained a manual merge:
```js
         init() { 
             let err = false; 
             if (this.gravity === true) 
                 this.gravity = Object.assign({},mec.gravity,{active:true}); 
             else if (!this.gravity) 
                 this.gravity = Object.assign({},mec.gravity,{active:false}); 
//...
            for (let i=0; i < this.nodes.length && !err; i++)
                err = this.nodes[i].init(this);
            for (let i=0; i < this.constraints.length && !err; i++)
                if (!this.constraints[i].initialized)  // possibly already initialized by referencing .. !
                    err = this.constraints[i].init(this);
            for (let i=0; i < this.loads.length && !err; i++)
                err = this.loads[i].init(this);
            for (let i=0; i < this.views.length && !err; i++)
                err = this.views[i].init(this);
            for (let i=0; i < this.shapes.length && !err; i++)
                err = this.shapes[i].init(this);

            return err;
}
```

`err` is now unused. Is this intended or went something wrong?
I also get TypeErrors when trying to define components with empty or missing `id`s. Shouldn't this be caught now or do i have a wrong idea of the error handling in `.init()`?

Edit: I know that valid ids are a requirement but does that mean that those are not checked for validity while initializing?

**Comment by goessner** [comment]
* Unused `err` variable removed.
* Clearing previous error in `model.state` now.
* Invalid references are always tested with `init` ... at least should be ...
* Missing references result in an error with nodes and constraints only and a warning with forces.

Please urgently  test after `model.init()` the flag `model.valid`. If it is true, you can test model.msg, which might contain a warning then for presentation to the user, and proceed with simulation.

Also read `remarks.md` in the `doc` folder.
