### ISSUE TITLE
property 'mode' added to view elements

### ISSUE THREAD

**Issue by goessner** [goessner/mec2#18]
please read [remarks.md](https://github.com/goessner/mec2/blob/master/doc/remarks.md) ...

**Comment by jauhl** [comment]
Cool feature.
Do I have to call `model.preview()` myself though? Wouldn’t it be smart to call that at the end of `model.init()` automatically in addition to user calls?

edit: 
Also it would be nice if `model.preview()` checked the validity of the model while solving and stopped/aborted when necessary.
