### ISSUE TITLE
mec.model.purgeNode()

### ISSUE THREAD

**Issue by jauhl** [goessner/mec2#2]
`mec.model.purgeNode()` does not remove all elements that depend on the passed node.

To reproduce please purge node 'B' of a standard fourbar linkage. Constraint 'c' will remain. This is due to this constraint rising up in its array after another constraints was removed. The index of the `for`-loop, where the deletion happens remains at its current value, skipping the constraint. 
This probably also happens when purging loads and shapes...

Proposed fix: 
Flag elements for removal while iterating their container-arrays (e.g. by writing their ids or indices to a temporary array) and remove them only when checking for dependencies is completed. Also remember to splice backwards if you saved indices instead of ids.

**Comment by jauhl** [comment]
Maybe implement

```javascript
adjConstraintIds() {
    let contraints = []
    for (const constraint of this.model.constraints) 
        if (constraint.dependsOn(this))
            contraints.push(constraint.id);
    return contraints;
},
```
to mec.node.js, it's needed for mecEdit anyway.

**Comment by goessner** [comment]
Seemed indeed a naive implementation by me.

Shouldn't we also need `adjLoadIds()`, `adjShapeIds()` here also ... ?

**Comment by goessner** [comment]
I propose a similar solution which scales a little better in future, when possibly other element types are added.

First a similar method to `model.hasDependents()` is needed:

```js
        /**
         * Get dependents of a specified element.
         * As a result a dictionary object containing dependent elements is created:
         * `{constraints:[], loads:[], shapes:[]}`
         * @method
         * @param {object} elem - element.
         * @returns {object} dictionary object containing dependent elements.
         */

        dependentsOf(elem) {
            const deps = {constraints:[],loads:[],shapes:[]};
            for (const constraint of this.constraints)
                if (constraint.dependsOn(elem))
                    deps.constraints.push(constraint);
            for (const load of this.loads)
                if (load.dependsOn(elem))
                    deps.loads.push(load);
            for (const shape of this.shapes)
                if (shape.dependsOn(elem))
                    deps.shapes.push(shape);
            return deps;
        }
```

Then a global purge routine working on such dictionaries is implemented:

```js
        /**
         * Purge all elements in an element dictionary.
         * @method
         * @param {object} elems - element dictionary.
         */
        purgeElements(elems) {
            for (const constraint of elems.constraints)
                this.constraints.splice(this.constraints.indexOf(constraint),1);
            for (const load of elems.loads)
                this.loads.splice(this.loads.indexOf(load),1);
            for (const shape of this.shapes)
                this.shapes.splice(this.shapes.indexOf(shape),1);
        },
```

Then the `model.purgeNode()` method reads as easy as ...

```js
        /**
         * Delete node and all depending elements from model.
         * @method
         * @param {object} node - node to remove.
         */
        purgeNode(node) {
            this.purgeElements(this.dependentsOf(node));
            this.nodes.splice(this.nodes.indexOf(node),1);
        },
```

as well as the other `model.purgeXXX()` routines.

What do you think. I implemented and tested it with the 'stress-test' model and see it working properly.

**Comment by jauhl** [comment]
This looks good. Haven't used other components apart from constraints and nodes yet, but i guess i'll need that dependsOf() method for them too.

**Comment by goessner** [comment]
Don't know, what you mean by `dependsOf()`.

* `model.dependentsOf(elem)` is sufficient to be a model method only.
* `dependsOn(elem)` is already implemented for all elements.
