### ISSUE TITLE
Shapes 'fix' & 'flt' no longer working.

### ISSUE THREAD

**Issue by jauhl** [goessner/mec2#23]
It seems that drawing shapes for fixed and floating nods has changed with some update of dependency g2 so that e.g. https://github.com/goessner/mec2/blob/99b21625aec21b5c94706fd449f91979636fcecb/src/mec.shape.js#L68-L70
no longer works.

Maybe @klawr can help out?

**Comment by klawr** [comment]
Can you give me an example to reproduce that bug?

On the other hand, I think it is deprecated to use the "mec" symbols in "use" since before I started working with g2.

Try
```
 draw(g) { 
     g.nodfix({x:()=>this.p.x,y:()=>this.p.y,w:this.w0 || 0}); 
 } 
```
instead.

**Comment by jauhl** [comment]
This works, Thanks.
