### ISSUE TITLE
charts - darkmode evaluation inverted?

### ISSUE THREAD

**Issue by jauhl** [goessner/mec2#30]
Testing darkmode for charts it didn't work for me. I then saw that the labelstyle was still set to black even though the darkmode-flag was `true`. I inverted
https://github.com/goessner/mec2/blob/9d0145b7968b008d0a54eb3eb6365787dfd9c951/src/mec.view.js#L468

to read
```js
const fs = this.model.env.show.darkmode ? 'black' : 'white';
```
and it worked, so something is not right...

Also, changing the darkmode-flag at runtime needs to change the labelstyle too, which is currently not the case. If this is not possible we need a static styling that is readable in all modes e.g. black text on white background.

**Comment by klawr** [comment]
The `fs` defines the color of the text. Does not seem to be inverted.
This gets evaluated at `model.init`. If darkmode is activated after initiation it will not be considered.
I see if i can get a nice solution.
