### ISSUE TITLE
chart ref property

### ISSUE THREAD

**Issue by jauhl** [goessner/mec2#33]
https://github.com/goessner/mec2/blob/4c34cc8946fdcabb53ded30a68e9ba7310a60ea3/src/mec.view.js#L516

Currently only ori-drives can be referenced although len-dof can have a drive too...
This might also be an issue at other places in the `mec.view.chart` object.

**Comment by klawr** [comment]
Could not find any other side effects, beside the fact that `len` was not considered when adding the `local_t` property. If you find any please let me know
