### ISSUE TITLE
Proposal: Performance/Precision Modes

### ISSUE THREAD

**Issue by jauhl** [goessner/mec2#35]
I would like to discuss the implementation of different precision settings/modes for mec2.

Either a `Boolean` flag e.g. `mec.performance` (for two modes) or a variable like `mec.precision` `[‘low’,’medium’,’high’]` could be set and evaluated when accessing properties that affect the runtime of the solver, e.g. `mec.asmItrMax`, `mec.itrMax`, `mec.velTol` or en-/disable the fps-dependency in `model.preview()`. 

They could become getters and look like  this for example `get asmItrMax() { return this.performance ? 256 : 512 }` instead of being static `asmItrMax: 512`.

Another solution, which wouldn’t negatively affect the current performance, would be if this flag (`mec.performance`) was made a setter that would change the static properties accordingly.

Please let me know what you think.

**Comment by goessner** [comment]
Well ... I like this proposal via `mec.precision` with `medium` the default value a lot. So changing properties to getters related to `mec.precision` makes sense and should work out of the box.
