### ISSUE TITLE
purging elements bugged due to charts

### ISSUE THREAD

**Issue by jauhl** [goessner/mec2#36]
When trying to purge elements e.g. by calling `model.purgeNode()` or `model.purgeConstraint()`, https://github.com/goessner/mec2/blob/a673b74b69be1b9a58c9ca9f9bad018d3bbcc023/src/mec.view.js#L523 throws a `TypeError: this.yaxis.some is not a function` if the model contains a chart. This happens regardless of where the chart is placed (main or side canvas).

See for yourself with this model:
```json
{
  "id":"purge bugged",
  "nodes": [
    { "id":"A","x":0,"y":0,"base":true },
    { "id":"B","x":0,"y":100 }
  ],
  "constraints": [
    { "id":"a","p1":"A","p2":"B","len":{ "type":"const" },"ori":{ "type":"drive","func":"sinoid","Dt":1,"Dw":6.283185307179586 } }
  ],
  "views": [
    { "as":"chart","x":40,"y":40,"b":200,"h":150,"t0":0.1,"Dt":1,"mode":"preview",
      "xaxis":{ "show":"w","of":"a" },
      "yaxis":{ "show":"wt","of":"a" }
    }
  ]
}
```

**Comment by goessner** [comment]
.. please do not close issues without a (short) comment ..

**Comment by jauhl** [comment]
Also, please be more thorough with your build process. `mec2.js` needs to be updated too.

**Comment by klawr** [comment]
I made a comment in the linked commit which closed the issue.

[dependsOn function referred to the wrong object.](https://github.com/goessner/mec2/commit/d3cdbc888fd1ef0d78e801d0d472343afd3feefe)

@jauhl didnt see that this is not part of build. Should we add concat to build?

**Comment by jauhl** [comment]
Please look at the scripts provided by `package.json` and use `npm run update` for example.

**Comment by goessner** [comment]
don't rely on people navigating to your code and look for / understand your changes.

**Comment by klawr** [comment]
It is standard procedure to add comments in git commit messages, but i can duplicate them in the issue tracker if you want me to.

Updated mec2.js in 6f0a6560f02556276efefd17f427b23f3cf10abd

I think the update script should replace the minify in build. Sorry for the mistake

**Comment by goessner** [comment]
yes ... so I need only to read the corresponding email and do not need to do two additional navigation-clicks.
