### ISSUE TITLE
JSON import / export needed

### ISSUE THREAD

**Issue by goessner** [goessner/mec2#4]
@jauhl : Please integrate the missing `JSON` import / export functions to mec2. Thanks.

**Comment by jauhl** [comment]
Export is now supported (except for some properties of ori or len type='drive') via model.toJSON().
Not sure if import is needed though. Shouldn’t this rather be handled by the apps?

**Comment by goessner** [comment]
It works like a charm due to `*.toJSON`. I would like to have a result document as minimal as the original, so  defaults shouldn't get serialized.

* `ori:{ type: 'free' }` is the default.
* Note: the second part of  `if (this.w0 && !(this.w0 === 0))` will never be evaluated. It's equivalent to `if (this.w0)`
* `obj.wref = this.wref;`  in `mec.load.js` doesn't resolve to the id.

Hmm .. I'm not so happy with JSON.stringify's default formatting. Willl think about it.

You are right. Import should be managed by the app simply via 

```js
delete app.model;
app.model = mec.model.extend(newModel);
```
Hopefully app doesn't hold any references into the old model then.

**Comment by goessner** [comment]
I found a more appealing solution regarding the JSON output formatting. JSON.stringify is not very customizable here. Look at the simple model ...
```js
const model = {
    id: 'pendulum',
    gravity:true,
    nodes: [
        { id:'A0',x:100,y:100,base:true },
        { id:'A', x:100,y:170 }
    ],
    constraints: [
        { id:'a',p1:'A0',p2:'A',len:{type:'const'} }
    ]
}
```
... the JSON output string is now ...
```json
{
  "id":"pendulum",
  "gravity":true,
  "nodes": [
    { "id":"A0","x":100,"y":100,"base":true },
    { "id":"A","x":100,"y":170 }
  ]
}
```
... only caring about the model and the nodes.

This is achieved with simple string composition (es6 template strings seem to have no advantage here) by `mec.model.asJSON()` 

```js
asJSON() {
    // dynamically create a JSON output string ...
    const nodeCnt = this.nodes.length;
    const comma = (i,n) => i < n-1 ? ',' : '';
    const str = '{'
              + '\n  "id":"'+this.id+'"'
              + (this.gravity.active ? ',\n  "gravity":true' : '') 
              + (nodeCnt ? ',\n  "nodes": [\n' : '')
              + (nodeCnt ? this.nodes.map((n,i) => '    '+n.asJSON()+comma(i,nodeCnt)+'\n').join('') : '')
              + (nodeCnt ? '  ]\n' : '')
              + '}';
    return str;
}
```
and `mec.node.asJSON()`
```js
asJSON() {
    return '{ "id":"'+this.id+'","x":'+this.x0+',"y":'+this.y0
         + (this.base ? ',"base":true' : '')
         + (this.idloc ? ',"idloc":"'+this.idloc : '')
         + ' }';
},
```
Watch out for the `comma` function above. This is due to the fact, that JSON disallows trailing commas.

What do you think about this? I will publish it as a proposal.

JSON formatting is too important to leave it to `JSON.stringify` :).

**Comment by jauhl** [comment]
I like your proposal. I will change my approach to yours. I already finished `asJSON()` for `mec.constraints` but will wait to commit until I am done with the other elements to have a more complete package. Still need to work on my punctuation though, as usual… 

![grafik](https://user-images.githubusercontent.com/19715408/43857173-d25ab84a-9b4a-11e8-8295-d816e7074dc6.png)

**Comment by jauhl** [comment]
What’s your take on linebreaks? Constraints can sometimes get very long:
![grafik](https://user-images.githubusercontent.com/19715408/43857420-8abd6fb8-9b4b-11e8-8107-c1b3334162f9.png)

**Comment by goessner** [comment]
The only things for linebreaks which come to mind are 'ori' and 'len' with 'constraints'.

I would leave it to you for now.

Please note, that recently only `input:true` is allowed. The app needs to figure out the corresponding slider by itself somehow. `output`is discarded completely.

**Comment by jauhl** [comment]
feature added

**Comment by goessner** [comment]
I think it is save to remove the `toJSON` methods completely now.
