### ISSUE TITLE
length reference label

### ISSUE THREAD

**Issue by jauhl** [goessner/mec2#5]
Referenced constraints only appear in labels when orientation is referenced, not for length. See:

```javascript
{
    id: 'len ref',
    nodes: [
        {id:'A0',x:100,y:100,base:true},
        {id:'A',x:100,y:200},
        {id:'B',x:300,y:200},
        {id:'B0',x:300,y:100,base:true},
    ],
    constraints: [
        { id:'a',p1:'A0',p2:'A',ori:{type:'const'} },
        { id:'b',p1:'B0', p2:'B',len:{type:'ref',ref:'a'},ori:{type:'const'} }
    ]
}
```
This renders:

![grafik](https://user-images.githubusercontent.com/19715408/43859572-5096d2ec-9b51-11e8-83be-9828b5305c0c.png)

Label b should read b(a).

**Comment by goessner** [comment]
.. ok, will have a look into this ...

**Comment by goessner** [comment]
Should be resolved with the current version .. please test.

**Comment by jauhl** [comment]
Labels do now contain length references. However, when length and orientation are referenced, only the ori ref is shown in the label.

**Comment by goessner** [comment]
Should work now .. please test.

**Comment by jauhl** [comment]
resolved
