### ISSUE TITLE
constraint order in model

### ISSUE THREAD

**Issue by jauhl** [goessner/mec2#6]
When defining models that contain references, those references have to be defined after the referenced constraint or else an error (e.g. `TypeError: len.ref.init is not a function`) is thrown. Maybe there is an easy way to hoist constraints, which do not contain an `ori` or `len` `type:’ref’` when initializing models to avoid possible model definition errors. 

This works:
```javascript
{
    id: 'len ref',
    nodes: [
        {id:'A0',x:100,y:100,base:true},
        {id:'A',x:100,y:200},
        {id:'B',x:300,y:200},
        {id:'B0',x:300,y:100,base:true},
    ],
    constraints: [
        { id:'a',p1:'A0',p2:'A',ori:{type:'const'} },
        { id:'b',p1:'B0', p2:'B',len:{type:'ref',ref:'a'},ori:{type:'const'} }
    ]
}
```
This doesn't:
```javascript
{
    id: 'len ref',
    nodes: [
        {id:'A0',x:100,y:100,base:true},
        {id:'A',x:100,y:200},
        {id:'B',x:300,y:200},
        {id:'B0',x:300,y:100,base:true},
    ],
    constraints: [
        { id:'b',p1:'B0', p2:'B',len:{type:'ref',ref:'a'},ori:{type:'const'} },
        { id:'a',p1:'A0',p2:'A',ori:{type:'const'} }
    ]
}
```

**Comment by goessner** [comment]
Will have a look into that later. Might be not so hard to fix that bug.

**Comment by goessner** [comment]
Should be resolved with the current version. Please test.

**Comment by jauhl** [comment]
resolved
